### ISSUE TITLE
Add Payment Screen

### ISSUE THREAD

**Issue by hoangoreki** [MuoiVung/F-Mock-Project#36]

**Comment by hoangoreki** [comment]
Em  bị lỗi phần navigate đến AddPayment anh xem qua giúp em được không ạ
 @MuoiVung

**Comment by MuoiVung** [comment]
@hoangoreki em pull main mới về, rồi merge lại với nhánh của em nhé.

Em tạo PaymentMethodNavigator nhưng chưa thay thế PaymentMethod trong cái ProfileNavigator.
Em chưa tạo type PaymentScreenProps mà đã dùng rồi.
Em vào đọc code, có gì không hiểu thì nhắn anh.
